# 设置关节角度/速度限制 (CAN 0x474 下发即返回, 协议无应答)
uint8 joint_num    #关节序号1~6
float32 max_angle  #最大角度限制 rad NaN不修改(填0x7FFF无效值)
float32 min_angle  #最小角度限制 rad NaN不修改
float32 max_speed  #最大关节速度 rad/s NaN不修改
---
bool success       #CAN 帧下发成功为 true
string message
